spring:
  profiles: product1
  application:
    name: shop-service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  #链路追踪的可视化配置 zipkin
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    sender:
      type: web #请求方式,默认以http的方式向zipkin server发送追踪数据
    sleuth:
      sampler:
        probability: 1.0 #采样的百分比

server:
  port: 9003

eureka:
  client:
    #Eureka服务端路径
    serviceUrl:
      defalutZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka
  instance:
    #使用IP注册
    prefer-ip-address: true
    #自定义注册名字 ，spring.cloud.client.ip-address为springcloud获取本机ip地址
    instance-id: ${spring.cloud.client.ip-address}-1:${server.port}

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG

---
spring:
  profiles: product2
  application:
    name: shop-service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  #链路追踪的可视化配置 zipkin
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    sender:
      type: web #请求方式,默认以http的方式向zipkin server发送追踪数据
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比


server:
  port: 9033

eureka:
  client:
    #Eureka服务端路径
    serviceUrl:
      defalutZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka
  instance:
    #使用IP注册
    prefer-ip-address: true
    #自定义注册名字 ，spring.cloud.client.ip-address为springcloud获取本机ip地址
    instance-id: ${spring.cloud.client.ip-address}-2:${server.port}

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
