server:
  port: 9004
spring:
  application:
    name: shop_service_user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

eureka:
  client:
    #Eureka服务端路径
    serviceUrl:
      defalutZone: http://localhost:8761/eureka/
  instance:
    #使用IP注册
    prefer-ip-address: true