server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    #是否将自己注册到Eureka服务中，自身无需注册
    register-with-eureka: false
    #是否从Eureka中获取注册信息
    fetch-registry: false
    #客户端与Eureka服务端进行交互的地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/