#指定应用名称 三横线是文件分割，在右上角启动中配置 edit Configurations中配置 active profiles中指定配置如：eureka1、eureka2
#这里的 hostname为eureka1、eureka2 在本机的hosts文件指定了这两个名字
spring:
  application:
    name: shop-eureka-server
---
#执行peer1的配置信息
spring:
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    #客户端与Eureka服务端进行交互的地址
    service-url:
      defaultZone: http://eureka2:8762/eureka
---
#执行peer2的配置信息
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
  client:
    #客户端与Eureka服务端进行交互的地址
    service-url:
      defaultZone: http://eureka1:8761/eureka